// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_MEMBER_VISITOR_H_
#define _BEHAVIAC_MEMBER_VISITOR_H_

#include "behaviac_agent_headers.h"

// Agent property and method handlers


namespace hero_decision
{
	struct PROPERTY_TYPE_hero_decision_Robot_ammo { };
	template<> inline int& Robot::_Get_Property_<PROPERTY_TYPE_hero_decision_Robot_ammo>()
	{
		return this->ammo;
	}

	struct PROPERTY_TYPE_hero_decision_Robot_combat_effective_num { };
	template<> inline int& Robot::_Get_Property_<PROPERTY_TYPE_hero_decision_Robot_combat_effective_num>()
	{
		return this->combat_effective_num;
	}

	struct PROPERTY_TYPE_hero_decision_Robot_combat_effectiveness { };
	template<> inline double& Robot::_Get_Property_<PROPERTY_TYPE_hero_decision_Robot_combat_effectiveness>()
	{
		return this->combat_effectiveness;
	}

	struct PROPERTY_TYPE_hero_decision_Robot_health { };
	template<> inline int& Robot::_Get_Property_<PROPERTY_TYPE_hero_decision_Robot_health>()
	{
		return this->health;
	}

	struct METHOD_TYPE_hero_decision_Robot_EngageRobot { };
	template<> inline behaviac::EBTStatus Robot::_Execute_Method_<METHOD_TYPE_hero_decision_Robot_EngageRobot>(behaviac::string p0)
	{
		return this->hero_decision::Robot::EngageRobot(p0);
	}

	struct METHOD_TYPE_hero_decision_Robot_Flee { };
	template<> inline void Robot::_Execute_Method_<METHOD_TYPE_hero_decision_Robot_Flee>()
	{
		this->hero_decision::Robot::Flee();
	}

	struct METHOD_TYPE_hero_decision_Robot_GoGetBuff { };
	template<> inline behaviac::EBTStatus Robot::_Execute_Method_<METHOD_TYPE_hero_decision_Robot_GoGetBuff>()
	{
		return this->hero_decision::Robot::GoGetBuff();
	}

	struct METHOD_TYPE_hero_decision_Robot_WaitForGameStart { };
	template<> inline behaviac::EBTStatus Robot::_Execute_Method_<METHOD_TYPE_hero_decision_Robot_WaitForGameStart>()
	{
		return this->hero_decision::Robot::WaitForGameStart();
	}

}

#endif // _BEHAVIAC_MEMBER_VISITOR_H_
