# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hero_msgs/BulletsInfo.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import hero_msgs.msg

class BulletsInfo(genpy.Message):
  _md5sum = "38e2196c2ea7bf8b960e57cec8261003"
  _type = "hero_msgs/BulletsInfo"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint32 bullet_num
hero_msgs/BulletMove[] bullets

================================================================================
MSG: hero_msgs/BulletMove
string owner
float64 x
float64 y
float64 x_last
float64 y_last
float64 yaw
float64 speed
float64 covered_distance
"""
  __slots__ = ['bullet_num','bullets']
  _slot_types = ['uint32','hero_msgs/BulletMove[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       bullet_num,bullets

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BulletsInfo, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.bullet_num is None:
        self.bullet_num = 0
      if self.bullets is None:
        self.bullets = []
    else:
      self.bullet_num = 0
      self.bullets = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_I().pack(self.bullet_num))
      length = len(self.bullets)
      buff.write(_struct_I.pack(length))
      for val1 in self.bullets:
        _x = val1.owner
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_7d().pack(_x.x, _x.y, _x.x_last, _x.y_last, _x.yaw, _x.speed, _x.covered_distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.bullets is None:
        self.bullets = None
      end = 0
      start = end
      end += 4
      (self.bullet_num,) = _get_struct_I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.bullets = []
      for i in range(0, length):
        val1 = hero_msgs.msg.BulletMove()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.owner = str[start:end].decode('utf-8')
        else:
          val1.owner = str[start:end]
        _x = val1
        start = end
        end += 56
        (_x.x, _x.y, _x.x_last, _x.y_last, _x.yaw, _x.speed, _x.covered_distance,) = _get_struct_7d().unpack(str[start:end])
        self.bullets.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_I().pack(self.bullet_num))
      length = len(self.bullets)
      buff.write(_struct_I.pack(length))
      for val1 in self.bullets:
        _x = val1.owner
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.pack('<I%ss'%length, length, _x))
        _x = val1
        buff.write(_get_struct_7d().pack(_x.x, _x.y, _x.x_last, _x.y_last, _x.yaw, _x.speed, _x.covered_distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.bullets is None:
        self.bullets = None
      end = 0
      start = end
      end += 4
      (self.bullet_num,) = _get_struct_I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.bullets = []
      for i in range(0, length):
        val1 = hero_msgs.msg.BulletMove()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.owner = str[start:end].decode('utf-8')
        else:
          val1.owner = str[start:end]
        _x = val1
        start = end
        end += 56
        (_x.x, _x.y, _x.x_last, _x.y_last, _x.yaw, _x.speed, _x.covered_distance,) = _get_struct_7d().unpack(str[start:end])
        self.bullets.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
