# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hero_msgs/GameSurvivor.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GameSurvivor(genpy.Message):
  _md5sum = "48420e310835d7d79e0a1b719e881088"
  _type = "hero_msgs/GameSurvivor"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """#robot survival
bool red3
bool red4
bool blue3
bool blue4
"""
  __slots__ = ['red3','red4','blue3','blue4']
  _slot_types = ['bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       red3,red4,blue3,blue4

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GameSurvivor, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.red3 is None:
        self.red3 = False
      if self.red4 is None:
        self.red4 = False
      if self.blue3 is None:
        self.blue3 = False
      if self.blue4 is None:
        self.blue4 = False
    else:
      self.red3 = False
      self.red4 = False
      self.blue3 = False
      self.blue4 = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.red3, _x.red4, _x.blue3, _x.blue4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.red3, _x.red4, _x.blue3, _x.blue4,) = _get_struct_4B().unpack(str[start:end])
      self.red3 = bool(self.red3)
      self.red4 = bool(self.red4)
      self.blue3 = bool(self.blue3)
      self.blue4 = bool(self.blue4)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.red3, _x.red4, _x.blue3, _x.blue4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.red3, _x.red4, _x.blue3, _x.blue4,) = _get_struct_4B().unpack(str[start:end])
      self.red3 = bool(self.red3)
      self.red4 = bool(self.red4)
      self.blue3 = bool(self.blue3)
      self.blue4 = bool(self.blue4)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B = None
def _get_struct_4B():
    global _struct_4B
    if _struct_4B is None:
        _struct_4B = struct.Struct("<4B")
    return _struct_4B
