(cl:defpackage hero_msgs-srv
  (:use )
  (:export
   "FRICWHL"
   "<FRICWHL-REQUEST>"
   "FRICWHL-REQUEST"
   "<FRICWHL-RESPONSE>"
   "FRICWHL-RESPONSE"
   "GIMBALMODE"
   "<GIMBALMODE-REQUEST>"
   "GIMBALMODE-REQUEST"
   "<GIMBALMODE-RESPONSE>"
   "GIMBALMODE-RESPONSE"
   "JUDGESYSCONTROL"
   "<JUDGESYSCONTROL-REQUEST>"
   "JUDGESYSCONTROL-REQUEST"
   "<JUDGESYSCONTROL-RESPONSE>"
   "JUDGESYSCONTROL-RESPONSE"
   "SHOOTCMD"
   "<SHOOTCMD-REQUEST>"
   "SHOOTCMD-REQUEST"
   "<SHOOTCMD-RESPONSE>"
   "SHOOTCMD-RESPONSE"
  ))

