// Generated by gencpp from file hero_msgs/BasicExecutorRequest.msg
// DO NOT EDIT!


#ifndef HERO_MSGS_MESSAGE_BASICEXECUTORREQUEST_H
#define HERO_MSGS_MESSAGE_BASICEXECUTORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hero_msgs
{
template <class ContainerAllocator>
struct BasicExecutorRequest_
{
  typedef BasicExecutorRequest_<ContainerAllocator> Type;

  BasicExecutorRequest_()
    : command(0)
    , robot_name()
    , yaw_control(false)
    , position_x(0.0)
    , position_y(0.0)  {
    }
  BasicExecutorRequest_(const ContainerAllocator& _alloc)
    : command(0)
    , robot_name(_alloc)
    , yaw_control(false)
    , position_x(0.0)
    , position_y(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _command_type;
  _command_type command;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_name_type;
  _robot_name_type robot_name;

   typedef uint8_t _yaw_control_type;
  _yaw_control_type yaw_control;

   typedef double _position_x_type;
  _position_x_type position_x;

   typedef double _position_y_type;
  _position_y_type position_y;



  enum {
    MOVE_TO_POSITION = 1u,
    ATTACK_ROBOT = 2u,
    HALT = 3u,
  };


  typedef boost::shared_ptr< ::hero_msgs::BasicExecutorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hero_msgs::BasicExecutorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct BasicExecutorRequest_

typedef ::hero_msgs::BasicExecutorRequest_<std::allocator<void> > BasicExecutorRequest;

typedef boost::shared_ptr< ::hero_msgs::BasicExecutorRequest > BasicExecutorRequestPtr;
typedef boost::shared_ptr< ::hero_msgs::BasicExecutorRequest const> BasicExecutorRequestConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hero_msgs::BasicExecutorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hero_msgs::BasicExecutorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hero_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hero_msgs': ['/home/ycz/ICRA_HERO_ws/devel/share/hero_msgs/msg', '/home/ycz/ICRA_HERO_ws/src/hero_msgs/msg', '/home/ycz/ICRA_HERO_ws/src/hero_msgs/msg/referee_system'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hero_msgs::BasicExecutorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hero_msgs::BasicExecutorRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hero_msgs::BasicExecutorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hero_msgs::BasicExecutorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_msgs::BasicExecutorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_msgs::BasicExecutorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hero_msgs::BasicExecutorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59e9b2222ab31692a62b743a59e7772a";
  }

  static const char* value(const ::hero_msgs::BasicExecutorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59e9b2222ab31692ULL;
  static const uint64_t static_value2 = 0xa62b743a59e7772aULL;
};

template<class ContainerAllocator>
struct DataType< ::hero_msgs::BasicExecutorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hero_msgs/BasicExecutorRequest";
  }

  static const char* value(const ::hero_msgs::BasicExecutorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hero_msgs::BasicExecutorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 MOVE_TO_POSITION = 1\n\
uint8 ATTACK_ROBOT = 2\n\
uint8 HALT = 3\n\
uint8 command\n\
string robot_name\n\
bool yaw_control\n\
float64 position_x\n\
float64 position_y\n\
";
  }

  static const char* value(const ::hero_msgs::BasicExecutorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hero_msgs::BasicExecutorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.robot_name);
      stream.next(m.yaw_control);
      stream.next(m.position_x);
      stream.next(m.position_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BasicExecutorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hero_msgs::BasicExecutorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hero_msgs::BasicExecutorRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
    s << indent << "robot_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_name);
    s << indent << "yaw_control: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.yaw_control);
    s << indent << "position_x: ";
    Printer<double>::stream(s, indent + "  ", v.position_x);
    s << indent << "position_y: ";
    Printer<double>::stream(s, indent + "  ", v.position_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HERO_MSGS_MESSAGE_BASICEXECUTORREQUEST_H
