// Generated by gencpp from file hero_msgs/BulletMove.msg
// DO NOT EDIT!


#ifndef HERO_MSGS_MESSAGE_BULLETMOVE_H
#define HERO_MSGS_MESSAGE_BULLETMOVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hero_msgs
{
template <class ContainerAllocator>
struct BulletMove_
{
  typedef BulletMove_<ContainerAllocator> Type;

  BulletMove_()
    : owner()
    , x(0.0)
    , y(0.0)
    , x_last(0.0)
    , y_last(0.0)
    , yaw(0.0)
    , speed(0.0)  {
    }
  BulletMove_(const ContainerAllocator& _alloc)
    : owner(_alloc)
    , x(0.0)
    , y(0.0)
    , x_last(0.0)
    , y_last(0.0)
    , yaw(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _owner_type;
  _owner_type owner;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _x_last_type;
  _x_last_type x_last;

   typedef double _y_last_type;
  _y_last_type y_last;

   typedef double _yaw_type;
  _yaw_type yaw;

   typedef double _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::hero_msgs::BulletMove_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hero_msgs::BulletMove_<ContainerAllocator> const> ConstPtr;

}; // struct BulletMove_

typedef ::hero_msgs::BulletMove_<std::allocator<void> > BulletMove;

typedef boost::shared_ptr< ::hero_msgs::BulletMove > BulletMovePtr;
typedef boost::shared_ptr< ::hero_msgs::BulletMove const> BulletMoveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hero_msgs::BulletMove_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hero_msgs::BulletMove_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hero_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hero_msgs': ['/home/ycz/ICRA_HERO_ws/devel/share/hero_msgs/msg', '/home/ycz/ICRA_HERO_ws/src/hero_msgs/msg', '/home/ycz/ICRA_HERO_ws/src/hero_msgs/msg/referee_system'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hero_msgs::BulletMove_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hero_msgs::BulletMove_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hero_msgs::BulletMove_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hero_msgs::BulletMove_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_msgs::BulletMove_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_msgs::BulletMove_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hero_msgs::BulletMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "584e9ba03268754685621bbbb5bf5de7";
  }

  static const char* value(const ::hero_msgs::BulletMove_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x584e9ba032687546ULL;
  static const uint64_t static_value2 = 0x85621bbbb5bf5de7ULL;
};

template<class ContainerAllocator>
struct DataType< ::hero_msgs::BulletMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hero_msgs/BulletMove";
  }

  static const char* value(const ::hero_msgs::BulletMove_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hero_msgs::BulletMove_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string owner\n\
float64 x\n\
float64 y\n\
float64 x_last\n\
float64 y_last\n\
float64 yaw\n\
float64 speed\n\
";
  }

  static const char* value(const ::hero_msgs::BulletMove_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hero_msgs::BulletMove_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.owner);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.x_last);
      stream.next(m.y_last);
      stream.next(m.yaw);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BulletMove_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hero_msgs::BulletMove_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hero_msgs::BulletMove_<ContainerAllocator>& v)
  {
    s << indent << "owner: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.owner);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "x_last: ";
    Printer<double>::stream(s, indent + "  ", v.x_last);
    s << indent << "y_last: ";
    Printer<double>::stream(s, indent + "  ", v.y_last);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HERO_MSGS_MESSAGE_BULLETMOVE_H
