// Generated by gencpp from file hero_msgs/BulletsInfo.msg
// DO NOT EDIT!


#ifndef HERO_MSGS_MESSAGE_BULLETSINFO_H
#define HERO_MSGS_MESSAGE_BULLETSINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <hero_msgs/BulletMove.h>

namespace hero_msgs
{
template <class ContainerAllocator>
struct BulletsInfo_
{
  typedef BulletsInfo_<ContainerAllocator> Type;

  BulletsInfo_()
    : bullet_num(0)
    , bullets()  {
    }
  BulletsInfo_(const ContainerAllocator& _alloc)
    : bullet_num(0)
    , bullets(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _bullet_num_type;
  _bullet_num_type bullet_num;

   typedef std::vector< ::hero_msgs::BulletMove_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::hero_msgs::BulletMove_<ContainerAllocator> >::other >  _bullets_type;
  _bullets_type bullets;





  typedef boost::shared_ptr< ::hero_msgs::BulletsInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hero_msgs::BulletsInfo_<ContainerAllocator> const> ConstPtr;

}; // struct BulletsInfo_

typedef ::hero_msgs::BulletsInfo_<std::allocator<void> > BulletsInfo;

typedef boost::shared_ptr< ::hero_msgs::BulletsInfo > BulletsInfoPtr;
typedef boost::shared_ptr< ::hero_msgs::BulletsInfo const> BulletsInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hero_msgs::BulletsInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hero_msgs::BulletsInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hero_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hero_msgs': ['/home/ycz/ICRA_HERO_ws/devel/share/hero_msgs/msg', '/home/ycz/ICRA_HERO_ws/src/hero_msgs/msg', '/home/ycz/ICRA_HERO_ws/src/hero_msgs/msg/referee_system'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hero_msgs::BulletsInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hero_msgs::BulletsInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hero_msgs::BulletsInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hero_msgs::BulletsInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_msgs::BulletsInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_msgs::BulletsInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hero_msgs::BulletsInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bdf8108add47e44ea1df95423235ef9c";
  }

  static const char* value(const ::hero_msgs::BulletsInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbdf8108add47e44eULL;
  static const uint64_t static_value2 = 0xa1df95423235ef9cULL;
};

template<class ContainerAllocator>
struct DataType< ::hero_msgs::BulletsInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hero_msgs/BulletsInfo";
  }

  static const char* value(const ::hero_msgs::BulletsInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hero_msgs::BulletsInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 bullet_num\n\
hero_msgs/BulletMove[] bullets\n\
\n\
================================================================================\n\
MSG: hero_msgs/BulletMove\n\
string owner\n\
float64 x\n\
float64 y\n\
float64 x_last\n\
float64 y_last\n\
float64 yaw\n\
float64 speed\n\
";
  }

  static const char* value(const ::hero_msgs::BulletsInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hero_msgs::BulletsInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bullet_num);
      stream.next(m.bullets);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BulletsInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hero_msgs::BulletsInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hero_msgs::BulletsInfo_<ContainerAllocator>& v)
  {
    s << indent << "bullet_num: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.bullet_num);
    s << indent << "bullets[]" << std::endl;
    for (size_t i = 0; i < v.bullets.size(); ++i)
    {
      s << indent << "  bullets[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hero_msgs::BulletMove_<ContainerAllocator> >::stream(s, indent + "    ", v.bullets[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HERO_MSGS_MESSAGE_BULLETSINFO_H
