// Generated by gencpp from file hero_msgs/GimbalAimRequest.msg
// DO NOT EDIT!


#ifndef HERO_MSGS_MESSAGE_GIMBALAIMREQUEST_H
#define HERO_MSGS_MESSAGE_GIMBALAIMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hero_msgs
{
template <class ContainerAllocator>
struct GimbalAimRequest_
{
  typedef GimbalAimRequest_<ContainerAllocator> Type;

  GimbalAimRequest_()
    : set_angle_absolute(0.0)  {
    }
  GimbalAimRequest_(const ContainerAllocator& _alloc)
    : set_angle_absolute(0.0)  {
  (void)_alloc;
    }



   typedef double _set_angle_absolute_type;
  _set_angle_absolute_type set_angle_absolute;





  typedef boost::shared_ptr< ::hero_msgs::GimbalAimRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hero_msgs::GimbalAimRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GimbalAimRequest_

typedef ::hero_msgs::GimbalAimRequest_<std::allocator<void> > GimbalAimRequest;

typedef boost::shared_ptr< ::hero_msgs::GimbalAimRequest > GimbalAimRequestPtr;
typedef boost::shared_ptr< ::hero_msgs::GimbalAimRequest const> GimbalAimRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hero_msgs::GimbalAimRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hero_msgs::GimbalAimRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hero_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'hero_msgs': ['/home/ycz/ICRA_HERO_ws/devel/share/hero_msgs/msg', '/home/ycz/ICRA_HERO_ws/src/hero_msgs/msg', '/home/ycz/ICRA_HERO_ws/src/hero_msgs/msg/referee_system'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hero_msgs::GimbalAimRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hero_msgs::GimbalAimRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hero_msgs::GimbalAimRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hero_msgs::GimbalAimRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_msgs::GimbalAimRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_msgs::GimbalAimRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hero_msgs::GimbalAimRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "71c9d0ba4f4a467ab563a59a1cb5cc7c";
  }

  static const char* value(const ::hero_msgs::GimbalAimRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x71c9d0ba4f4a467aULL;
  static const uint64_t static_value2 = 0xb563a59a1cb5cc7cULL;
};

template<class ContainerAllocator>
struct DataType< ::hero_msgs::GimbalAimRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hero_msgs/GimbalAimRequest";
  }

  static const char* value(const ::hero_msgs::GimbalAimRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hero_msgs::GimbalAimRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 set_angle_absolute\n\
";
  }

  static const char* value(const ::hero_msgs::GimbalAimRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hero_msgs::GimbalAimRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.set_angle_absolute);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GimbalAimRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hero_msgs::GimbalAimRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hero_msgs::GimbalAimRequest_<ContainerAllocator>& v)
  {
    s << indent << "set_angle_absolute: ";
    Printer<double>::stream(s, indent + "  ", v.set_angle_absolute);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HERO_MSGS_MESSAGE_GIMBALAIMREQUEST_H
