// Generated by gencpp from file hero_msgs/GimbalAim.msg
// DO NOT EDIT!


#ifndef HERO_MSGS_MESSAGE_GIMBALAIM_H
#define HERO_MSGS_MESSAGE_GIMBALAIM_H

#include <ros/service_traits.h>


#include <hero_msgs/GimbalAimRequest.h>
#include <hero_msgs/GimbalAimResponse.h>


namespace hero_msgs
{

struct GimbalAim
{

typedef GimbalAimRequest Request;
typedef GimbalAimResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GimbalAim
} // namespace hero_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hero_msgs::GimbalAim > {
  static const char* value()
  {
    return "092644b5ad06ae027152ed41585220f2";
  }

  static const char* value(const ::hero_msgs::GimbalAim&) { return value(); }
};

template<>
struct DataType< ::hero_msgs::GimbalAim > {
  static const char* value()
  {
    return "hero_msgs/GimbalAim";
  }

  static const char* value(const ::hero_msgs::GimbalAim&) { return value(); }
};


// service_traits::MD5Sum< ::hero_msgs::GimbalAimRequest> should match 
// service_traits::MD5Sum< ::hero_msgs::GimbalAim > 
template<>
struct MD5Sum< ::hero_msgs::GimbalAimRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hero_msgs::GimbalAim >::value();
  }
  static const char* value(const ::hero_msgs::GimbalAimRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hero_msgs::GimbalAimRequest> should match 
// service_traits::DataType< ::hero_msgs::GimbalAim > 
template<>
struct DataType< ::hero_msgs::GimbalAimRequest>
{
  static const char* value()
  {
    return DataType< ::hero_msgs::GimbalAim >::value();
  }
  static const char* value(const ::hero_msgs::GimbalAimRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hero_msgs::GimbalAimResponse> should match 
// service_traits::MD5Sum< ::hero_msgs::GimbalAim > 
template<>
struct MD5Sum< ::hero_msgs::GimbalAimResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hero_msgs::GimbalAim >::value();
  }
  static const char* value(const ::hero_msgs::GimbalAimResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hero_msgs::GimbalAimResponse> should match 
// service_traits::DataType< ::hero_msgs::GimbalAim > 
template<>
struct DataType< ::hero_msgs::GimbalAimResponse>
{
  static const char* value()
  {
    return DataType< ::hero_msgs::GimbalAim >::value();
  }
  static const char* value(const ::hero_msgs::GimbalAimResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HERO_MSGS_MESSAGE_GIMBALAIM_H
