// Generated by gencpp from file hero_msgs/JudgeSysControlRequest.msg
// DO NOT EDIT!


#ifndef HERO_MSGS_MESSAGE_JUDGESYSCONTROLREQUEST_H
#define HERO_MSGS_MESSAGE_JUDGESYSCONTROLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hero_msgs
{
template <class ContainerAllocator>
struct JudgeSysControlRequest_
{
  typedef JudgeSysControlRequest_<ContainerAllocator> Type;

  JudgeSysControlRequest_()
    : command(0)
    , robot_name()  {
    }
  JudgeSysControlRequest_(const ContainerAllocator& _alloc)
    : command(0)
    , robot_name(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _command_type;
  _command_type command;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _robot_name_type;
  _robot_name_type robot_name;





  typedef boost::shared_ptr< ::hero_msgs::JudgeSysControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hero_msgs::JudgeSysControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct JudgeSysControlRequest_

typedef ::hero_msgs::JudgeSysControlRequest_<std::allocator<void> > JudgeSysControlRequest;

typedef boost::shared_ptr< ::hero_msgs::JudgeSysControlRequest > JudgeSysControlRequestPtr;
typedef boost::shared_ptr< ::hero_msgs::JudgeSysControlRequest const> JudgeSysControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hero_msgs::JudgeSysControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hero_msgs::JudgeSysControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hero_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hero_msgs': ['/home/ycz/ICRA_HERO_ws/devel/share/hero_msgs/msg', '/home/ycz/ICRA_HERO_ws/src/hero_msgs/msg', '/home/ycz/ICRA_HERO_ws/src/hero_msgs/msg/referee_system'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hero_msgs::JudgeSysControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hero_msgs::JudgeSysControlRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hero_msgs::JudgeSysControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hero_msgs::JudgeSysControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_msgs::JudgeSysControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_msgs::JudgeSysControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hero_msgs::JudgeSysControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "33ff8353b267f35f5b5ffce93cd8fb0b";
  }

  static const char* value(const ::hero_msgs::JudgeSysControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x33ff8353b267f35fULL;
  static const uint64_t static_value2 = 0x5b5ffce93cd8fb0bULL;
};

template<class ContainerAllocator>
struct DataType< ::hero_msgs::JudgeSysControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hero_msgs/JudgeSysControlRequest";
  }

  static const char* value(const ::hero_msgs::JudgeSysControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hero_msgs::JudgeSysControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 command\n\
string robot_name\n\
";
  }

  static const char* value(const ::hero_msgs::JudgeSysControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hero_msgs::JudgeSysControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
      stream.next(m.robot_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JudgeSysControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hero_msgs::JudgeSysControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hero_msgs::JudgeSysControlRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<int32_t>::stream(s, indent + "  ", v.command);
    s << indent << "robot_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.robot_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HERO_MSGS_MESSAGE_JUDGESYSCONTROLREQUEST_H
