// Generated by gencpp from file hero_msgs/JudgeSysControl.msg
// DO NOT EDIT!


#ifndef HERO_MSGS_MESSAGE_JUDGESYSCONTROL_H
#define HERO_MSGS_MESSAGE_JUDGESYSCONTROL_H

#include <ros/service_traits.h>


#include <hero_msgs/JudgeSysControlRequest.h>
#include <hero_msgs/JudgeSysControlResponse.h>


namespace hero_msgs
{

struct JudgeSysControl
{

typedef JudgeSysControlRequest Request;
typedef JudgeSysControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JudgeSysControl
} // namespace hero_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hero_msgs::JudgeSysControl > {
  static const char* value()
  {
    return "88842955bcbf0eaf028f22a76f978663";
  }

  static const char* value(const ::hero_msgs::JudgeSysControl&) { return value(); }
};

template<>
struct DataType< ::hero_msgs::JudgeSysControl > {
  static const char* value()
  {
    return "hero_msgs/JudgeSysControl";
  }

  static const char* value(const ::hero_msgs::JudgeSysControl&) { return value(); }
};


// service_traits::MD5Sum< ::hero_msgs::JudgeSysControlRequest> should match 
// service_traits::MD5Sum< ::hero_msgs::JudgeSysControl > 
template<>
struct MD5Sum< ::hero_msgs::JudgeSysControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hero_msgs::JudgeSysControl >::value();
  }
  static const char* value(const ::hero_msgs::JudgeSysControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hero_msgs::JudgeSysControlRequest> should match 
// service_traits::DataType< ::hero_msgs::JudgeSysControl > 
template<>
struct DataType< ::hero_msgs::JudgeSysControlRequest>
{
  static const char* value()
  {
    return DataType< ::hero_msgs::JudgeSysControl >::value();
  }
  static const char* value(const ::hero_msgs::JudgeSysControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hero_msgs::JudgeSysControlResponse> should match 
// service_traits::MD5Sum< ::hero_msgs::JudgeSysControl > 
template<>
struct MD5Sum< ::hero_msgs::JudgeSysControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hero_msgs::JudgeSysControl >::value();
  }
  static const char* value(const ::hero_msgs::JudgeSysControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hero_msgs::JudgeSysControlResponse> should match 
// service_traits::DataType< ::hero_msgs::JudgeSysControl > 
template<>
struct DataType< ::hero_msgs::JudgeSysControlResponse>
{
  static const char* value()
  {
    return DataType< ::hero_msgs::JudgeSysControl >::value();
  }
  static const char* value(const ::hero_msgs::JudgeSysControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HERO_MSGS_MESSAGE_JUDGESYSCONTROL_H
