// Generated by gencpp from file hero_msgs/MovePoint.msg
// DO NOT EDIT!


#ifndef HERO_MSGS_MESSAGE_MOVEPOINT_H
#define HERO_MSGS_MESSAGE_MOVEPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hero_msgs
{
template <class ContainerAllocator>
struct MovePoint_
{
  typedef MovePoint_<ContainerAllocator> Type;

  MovePoint_()
    : target_x(0.0)
    , target_y(0.0)
    , cmd_code(0)  {
    }
  MovePoint_(const ContainerAllocator& _alloc)
    : target_x(0.0)
    , target_y(0.0)
    , cmd_code(0)  {
  (void)_alloc;
    }



   typedef double _target_x_type;
  _target_x_type target_x;

   typedef double _target_y_type;
  _target_y_type target_y;

   typedef uint8_t _cmd_code_type;
  _cmd_code_type cmd_code;



  enum {
    MOVE = 0u,
    CANCEL = 1u,
  };


  typedef boost::shared_ptr< ::hero_msgs::MovePoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hero_msgs::MovePoint_<ContainerAllocator> const> ConstPtr;

}; // struct MovePoint_

typedef ::hero_msgs::MovePoint_<std::allocator<void> > MovePoint;

typedef boost::shared_ptr< ::hero_msgs::MovePoint > MovePointPtr;
typedef boost::shared_ptr< ::hero_msgs::MovePoint const> MovePointConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hero_msgs::MovePoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hero_msgs::MovePoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hero_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'hero_msgs': ['/home/ycz/ICRA_HERO_ws/devel/share/hero_msgs/msg', '/home/ycz/ICRA_HERO_ws/src/hero_msgs/msg', '/home/ycz/ICRA_HERO_ws/src/hero_msgs/msg/referee_system'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hero_msgs::MovePoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hero_msgs::MovePoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hero_msgs::MovePoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hero_msgs::MovePoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_msgs::MovePoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_msgs::MovePoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hero_msgs::MovePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8332454d4f4776c0538a4b89b1467de8";
  }

  static const char* value(const ::hero_msgs::MovePoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8332454d4f4776c0ULL;
  static const uint64_t static_value2 = 0x538a4b89b1467de8ULL;
};

template<class ContainerAllocator>
struct DataType< ::hero_msgs::MovePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hero_msgs/MovePoint";
  }

  static const char* value(const ::hero_msgs::MovePoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hero_msgs::MovePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 target_x\n\
float64 target_y\n\
uint8 cmd_code\n\
uint8 MOVE = 0\n\
uint8 CANCEL = 1\n\
\n\
\n\
";
  }

  static const char* value(const ::hero_msgs::MovePoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hero_msgs::MovePoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_x);
      stream.next(m.target_y);
      stream.next(m.cmd_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MovePoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hero_msgs::MovePoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hero_msgs::MovePoint_<ContainerAllocator>& v)
  {
    s << indent << "target_x: ";
    Printer<double>::stream(s, indent + "  ", v.target_x);
    s << indent << "target_y: ";
    Printer<double>::stream(s, indent + "  ", v.target_y);
    s << indent << "cmd_code: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cmd_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HERO_MSGS_MESSAGE_MOVEPOINT_H
