// Generated by gencpp from file hero_msgs/ProjectileSupply.msg
// DO NOT EDIT!


#ifndef HERO_MSGS_MESSAGE_PROJECTILESUPPLY_H
#define HERO_MSGS_MESSAGE_PROJECTILESUPPLY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hero_msgs
{
template <class ContainerAllocator>
struct ProjectileSupply_
{
  typedef ProjectileSupply_<ContainerAllocator> Type;

  ProjectileSupply_()
    : number(0)  {
    }
  ProjectileSupply_(const ContainerAllocator& _alloc)
    : number(0)  {
  (void)_alloc;
    }



   typedef uint8_t _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::hero_msgs::ProjectileSupply_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hero_msgs::ProjectileSupply_<ContainerAllocator> const> ConstPtr;

}; // struct ProjectileSupply_

typedef ::hero_msgs::ProjectileSupply_<std::allocator<void> > ProjectileSupply;

typedef boost::shared_ptr< ::hero_msgs::ProjectileSupply > ProjectileSupplyPtr;
typedef boost::shared_ptr< ::hero_msgs::ProjectileSupply const> ProjectileSupplyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hero_msgs::ProjectileSupply_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hero_msgs::ProjectileSupply_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hero_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'hero_msgs': ['/home/ycz/ICRA_HERO_ws/devel/share/hero_msgs/msg', '/home/ycz/ICRA_HERO_ws/src/hero_msgs/msg', '/home/ycz/ICRA_HERO_ws/src/hero_msgs/msg/referee_system'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hero_msgs::ProjectileSupply_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hero_msgs::ProjectileSupply_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hero_msgs::ProjectileSupply_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hero_msgs::ProjectileSupply_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_msgs::ProjectileSupply_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_msgs::ProjectileSupply_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hero_msgs::ProjectileSupply_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29e94f7568510a2f9241abcc8f191b4f";
  }

  static const char* value(const ::hero_msgs::ProjectileSupply_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29e94f7568510a2fULL;
  static const uint64_t static_value2 = 0x9241abcc8f191b4fULL;
};

template<class ContainerAllocator>
struct DataType< ::hero_msgs::ProjectileSupply_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hero_msgs/ProjectileSupply";
  }

  static const char* value(const ::hero_msgs::ProjectileSupply_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hero_msgs::ProjectileSupply_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#projectile supply\n\
uint8 number\n\
";
  }

  static const char* value(const ::hero_msgs::ProjectileSupply_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hero_msgs::ProjectileSupply_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProjectileSupply_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hero_msgs::ProjectileSupply_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hero_msgs::ProjectileSupply_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HERO_MSGS_MESSAGE_PROJECTILESUPPLY_H
