// Generated by gencpp from file hero_msgs/ShootCmd.msg
// DO NOT EDIT!


#ifndef HERO_MSGS_MESSAGE_SHOOTCMD_H
#define HERO_MSGS_MESSAGE_SHOOTCMD_H

#include <ros/service_traits.h>


#include <hero_msgs/ShootCmdRequest.h>
#include <hero_msgs/ShootCmdResponse.h>


namespace hero_msgs
{

struct ShootCmd
{

typedef ShootCmdRequest Request;
typedef ShootCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ShootCmd
} // namespace hero_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hero_msgs::ShootCmd > {
  static const char* value()
  {
    return "4adbabcc97afbd3e618602740ecc0659";
  }

  static const char* value(const ::hero_msgs::ShootCmd&) { return value(); }
};

template<>
struct DataType< ::hero_msgs::ShootCmd > {
  static const char* value()
  {
    return "hero_msgs/ShootCmd";
  }

  static const char* value(const ::hero_msgs::ShootCmd&) { return value(); }
};


// service_traits::MD5Sum< ::hero_msgs::ShootCmdRequest> should match 
// service_traits::MD5Sum< ::hero_msgs::ShootCmd > 
template<>
struct MD5Sum< ::hero_msgs::ShootCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hero_msgs::ShootCmd >::value();
  }
  static const char* value(const ::hero_msgs::ShootCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hero_msgs::ShootCmdRequest> should match 
// service_traits::DataType< ::hero_msgs::ShootCmd > 
template<>
struct DataType< ::hero_msgs::ShootCmdRequest>
{
  static const char* value()
  {
    return DataType< ::hero_msgs::ShootCmd >::value();
  }
  static const char* value(const ::hero_msgs::ShootCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hero_msgs::ShootCmdResponse> should match 
// service_traits::MD5Sum< ::hero_msgs::ShootCmd > 
template<>
struct MD5Sum< ::hero_msgs::ShootCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hero_msgs::ShootCmd >::value();
  }
  static const char* value(const ::hero_msgs::ShootCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hero_msgs::ShootCmdResponse> should match 
// service_traits::DataType< ::hero_msgs::ShootCmd > 
template<>
struct DataType< ::hero_msgs::ShootCmdResponse>
{
  static const char* value()
  {
    return DataType< ::hero_msgs::ShootCmd >::value();
  }
  static const char* value(const ::hero_msgs::ShootCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HERO_MSGS_MESSAGE_SHOOTCMD_H
