// Generated by gencpp from file hero_msgs/ShootCmdRequest.msg
// DO NOT EDIT!


#ifndef HERO_MSGS_MESSAGE_SHOOTCMDREQUEST_H
#define HERO_MSGS_MESSAGE_SHOOTCMDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hero_msgs
{
template <class ContainerAllocator>
struct ShootCmdRequest_
{
  typedef ShootCmdRequest_<ContainerAllocator> Type;

  ShootCmdRequest_()
    : mode(0)
    , number(0)  {
    }
  ShootCmdRequest_(const ContainerAllocator& _alloc)
    : mode(0)
    , number(0)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef uint8_t _number_type;
  _number_type number;



  enum {
    STOP = 0u,
    ONCE = 1u,
    CONTINUOUS = 2u,
  };


  typedef boost::shared_ptr< ::hero_msgs::ShootCmdRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hero_msgs::ShootCmdRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ShootCmdRequest_

typedef ::hero_msgs::ShootCmdRequest_<std::allocator<void> > ShootCmdRequest;

typedef boost::shared_ptr< ::hero_msgs::ShootCmdRequest > ShootCmdRequestPtr;
typedef boost::shared_ptr< ::hero_msgs::ShootCmdRequest const> ShootCmdRequestConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hero_msgs::ShootCmdRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hero_msgs::ShootCmdRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hero_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'hero_msgs': ['/home/ycz/ICRA_HERO_ws/devel/share/hero_msgs/msg', '/home/ycz/ICRA_HERO_ws/src/hero_msgs/msg', '/home/ycz/ICRA_HERO_ws/src/hero_msgs/msg/referee_system'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hero_msgs::ShootCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hero_msgs::ShootCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hero_msgs::ShootCmdRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hero_msgs::ShootCmdRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_msgs::ShootCmdRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hero_msgs::ShootCmdRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hero_msgs::ShootCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e60d1d1007f97ae14e2d2f584fbf2502";
  }

  static const char* value(const ::hero_msgs::ShootCmdRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe60d1d1007f97ae1ULL;
  static const uint64_t static_value2 = 0x4e2d2f584fbf2502ULL;
};

template<class ContainerAllocator>
struct DataType< ::hero_msgs::ShootCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hero_msgs/ShootCmdRequest";
  }

  static const char* value(const ::hero_msgs::ShootCmdRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hero_msgs::ShootCmdRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 STOP = 0\n\
uint8 ONCE = 1\n\
uint8 CONTINUOUS = 2\n\
uint8 mode\n\
uint8 number\n\
";
  }

  static const char* value(const ::hero_msgs::ShootCmdRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hero_msgs::ShootCmdRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShootCmdRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hero_msgs::ShootCmdRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hero_msgs::ShootCmdRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "number: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HERO_MSGS_MESSAGE_SHOOTCMDREQUEST_H
